[build]
  command   = "npm run build"
  publish   = ".next"

[dev]
  command   = "npm start"
  port      = 3000 

[context.production.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-nextjs" 